name: Deploy ECS Service

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: notification-service
  ECS_CLUSTER: nikhil-main-cluster
  ECS_SERVICE: notification-service
  TF_DIR: 02-service-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      # Step 1: Create only the ECR repo first
      # IMPORTANT: change aws_ecr_repository.this if your Terraform resource has a different name
      - name: Create ECR repository first
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform apply -auto-approve \
            -target=aws_ecr_repository.notification_service

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 2: Build and push image with GitHub SHA tag
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY ./app
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Step 3: Deploy ECS using the pushed image tag
      - name: Terraform Apply ECS service
        working-directory: ${{ env.TF_DIR }}
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          terraform apply -auto-approve \
            -var="image_tag=$IMAGE_TAG"